[package]
name = "ui"
license.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
version.workspace = true

[dependencies]
dioxus = { workspace = true }
server = { workspace = true }
